### ISSUE TITLE
Limit local pickup time slots, from being selected by a maximum # of customers

### ISSUE THREAD

**Issue by JayneNew** [mattbanks/woocommerce-local-pickup-time#82] opened 2020-04-28 09:03 UTC
In these times of Covid-19, limiting the number of people in store at any given time, and in order to provide great customer service it would be ideal if we could limit the number of times a specific pick-up time could be selected.  

ie:  limit local pick-up time of 6:00pm to being selected a maximum of 4 times

This could be done on a time slot basis or daily basis.  The per time slot basis may be onerous on screen but may provide advantages to spread the pickup times and limit people in store during peak times. 

If a pickup time reaches the limit, it is greyed out and not able to be selected by the customer. 

An alert may need to be in place if all time slots are taken, to open up time slots to a new maximum and ensure new customers can continue to order and choose pick-up times. 

Thank you for your consideration. 

Kind regards, 
Jayne

**Comment by timnolte** [comment] 2020-04-29 03:09
@JayneNew this is a duplicate of an existing open issue #68

**Closed by timnolte** 2020-04-29 03:09 UTC
Labels: duplicate
