### ISSUE TITLE
pickup time delay not respected

### ISSUE THREAD

**Issue by tomaski** [mattbanks/woocommerce-local-pickup-time#73] opened 2020-03-19 14:48 UTC
as I'm writing this, it's 15:47 and am able to select pickup 16:00 

pickup time delay is set to 30 min
timezone is correct

**Comment by timnolte** [comment] 2020-03-19 20:41
Can you provide me all of the following:

- Website URL
- PHP Version
- WordPress Version
- WooCommerce Version
- Plugin Version
- WordPress Timezone Setting
- WordPress Date Format Setting
- WordPress Time Format Setting
- All Plugin Start/End Pickup Time Settings
- Plugin Pickup Time Interval Setting
- Plugin Pickup Time Delay Setting
- Plugin Pickup Time Open Days Ahead Setting

**Comment by tomaski** [comment] 2020-03-19 20:59
Sure thing,

- URL: http://www.brafoer.nl/bezorgen
- PHP: 7.3.15
- WP: 5.3.2
- WC: 3.9.1
- Plugin: 1.3.11
- timezone: UTC+1
- date format: d-m-Y
- time format: H:i
- start pickup 16:00 (every day)
- end pickup 21:00 (every day)
- time interval: 30 min
- time delay: 30 min
- days ahead: 1

**Comment by timnolte** [comment] 2020-03-19 21:22
@tomaski OK, the fact that you are using UTC+1 for your Timezone is probably the problem. While those options are available in WP they are not recommended as they cause a lot of problems with date/time calculations.

**Comment by tomaski** [comment] 2020-03-19 21:39
@timnolte but it is my timezone and same thing happened when I had the time zone set to Europe/Amsterdam. What are the recommended settings then?
btw I did notice that the plugin uses american date format: m/d/y instead of the european: d/m/y - can it matter?

**Comment by timnolte** [comment] 2020-03-19 22:08
The only place that uses the U.S. date format is with the closed days list. All other cases it's using your WordPress date/time formats.

**Comment by timnolte** [comment] 2020-03-19 22:11
I should also ask, you didn't by chance leave the checkout screen up for a long time? The pickup time dropdown only checks the settings when it's generated and not afterwards. I do have an open ticket to do some additional validation around that aspect.

**Comment by timnolte** [comment] 2020-03-19 22:14
I will setup a test environment to match your setup and try to recreate to determine the issue. In general using an offset for your Timezone (UTC+1) is problematic and I can't really guarantee it'll work, especially because of places that observe daylight savings time. Using Europe/Amsterdam should have resolved the issue if that truly is your Timezone.

**Comment by tomaski** [comment] 2020-03-20 00:38
No, I did not leave it open. I am aware of that issue, as I am the one who opened it, a year ago xD

Anyway, the reason I switched to UTC+1 is that Europe/Amsterdam did not work.

**Comment by timnolte** [comment] 2020-03-20 01:46
@tomaski ah, OK, is this a new install, or did it quite working? I know that I spent some time awhile ago sorting through all of this including a bug between PHP versions. However, I'd like to know what may be the cause of it, especially given that I haven't received any other reports of it not working. I know there were some date/time changes in WordPress core not long ago, maybe that is the cause. Thanks!

**Comment by tomaski** [comment] 2020-03-20 17:06
@timnolte this is an old install. I just keep it up to date and client brought this to my attention only recently, so hard to tell what might have been the cause

**Comment by timnolte** [comment] 2020-03-21 18:57
A possible related report: https://wordpress.org/support/topic/pickup-time-delay/#post-12568883

**Comment by tomaski** [comment] 2020-03-24 14:04
@timnolte I think the issue is with how timestamps are stored in the database.
I am currently working on a webhook that is dealing with the data sent by WooCommerce on order completed. I chose 18:00 for the pickup, but the saved value is `1585072800` which translates to 19:00
can you investigate?

**Comment by timnolte** [comment] 2020-03-24 14:16
@tomaski does your location observe daylight savings time? If it does and you are using UTC+1 then that's the problem. UTC values don't recognize daylight savings time.

And yes, I'm trying to juggle a lot right now with COVID-19 so hopefully I'll have something figured out in the next day or two. This plugin isn't my part of my day job so it's completely on my own time. Thanks for digging in and providing those details, hopefully that will help me track down the issue, though I'm still at a loss because I haven't changed any of this code for over a year so there has to be something else going on for it to just be broken all of a sudden.

**Comment by tomaski** [comment] 2020-03-24 18:32
@timnolte  yes we do observe DST here, in the Netherlands. To be 100% honest with you before that COVID-19 pandemic, the client (restaurant) was receiving 2-3 orders a week. Right now the pickup/delivery is the only way they can operate so the issue got noticed pretty quickly. It could be that this timis issue was broken all along, but due to the low amount of orders it just wasn't noticed

**Comment by timnolte** [comment] 2020-03-24 18:45
OK, then that explains it. This means that you have to make sure the site Timezone is not using a UTC offset otherwise there is now way for the math to account for daylight savings.

**Comment by timnolte** [comment] 2020-03-26 08:25
@tomaski this should be fixed now on the version I just released. Please update the site and confirm. Thanks!

**Closed** 2020-03-27 03:55 UTC
Labels: bug, pending release

**Comment by tomaski** [comment] 2020-03-28 17:23
hey @timnolte yes, it does now! thx a lot, man! 👍
